# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d9d61c28-ac6b-49fc-b544-b6d95a4094fc";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6911-D67A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/data" = 
    { device = "/dev/disk/by-uuid/B29EF87A9EF83885";
      fsType = "ntfs";
      options = [ "defaults" "noatime" "nofail"];
    };
 
  fileSystems."/mnt/media" = 
    { device = "//192.168.40.245/bex";
      fsType = "cifs";
      options = [
	"credentials=/etc/nixos/hosts/desktop/smb-secrets"
	"x-systemd.automount"
	"noauto"
	"nofail"
	"uid=0"
 	"gid=0"
 	"file_mode=0777"
 	"dir_mode=0777"
 	"rw" # Ensure read-write option is also present
      ]; 
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;
  systemd.services.bluetooth.enable = true;
}
